name: adi_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.3.0
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "./assets/icon.png"

flutter:
  uses-material-design: true
